[2021-10-21 12:03:06,767] {processor.py:163} INFO - Started process (PID=22488) to work on /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:03:06,768] {processor.py:620} INFO - Processing file /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py for tasks to queue
[2021-10-21 12:03:06,768] {logging_mixin.py:109} INFO - [2021-10-21 12:03:06,768] {dagbag.py:500} INFO - Filling up the DagBag from /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:03:06,773] {logging_mixin.py:109} INFO - [2021-10-21 12:03:06,772] {dagbag.py:334} ERROR - Failed to import: /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py", line 49, in <module>
    t2 = BashOperator(
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 547, in __init__
    validate_key(task_id)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/utils/helpers.py", line 52, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key (print stuff) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-10-21 12:03:06,785] {processor.py:634} WARNING - No viable dags retrieved from /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:03:06,787] {processor.py:171} INFO - Processing /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py took 0.020 seconds
[2021-10-21 12:04:14,696] {processor.py:163} INFO - Started process (PID=22593) to work on /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:04:14,697] {processor.py:620} INFO - Processing file /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py for tasks to queue
[2021-10-21 12:04:14,697] {logging_mixin.py:109} INFO - [2021-10-21 12:04:14,697] {dagbag.py:500} INFO - Filling up the DagBag from /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:04:14,701] {logging_mixin.py:109} INFO - [2021-10-21 12:04:14,700] {dagbag.py:334} ERROR - Failed to import: /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py", line 49, in <module>
    t2 = BashOperator(
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 547, in __init__
    validate_key(task_id)
  File "/opt/anaconda3/envs/af2/lib/python3.8/site-packages/airflow/utils/helpers.py", line 52, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key (print stuff) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-10-21 12:04:14,713] {processor.py:634} WARNING - No viable dags retrieved from /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py
[2021-10-21 12:04:14,715] {processor.py:171} INFO - Processing /Users/cesareborgia/Desktop/9fwr/airflow/dags/tutorial.py took 0.019 seconds
